<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6baf09b0-e28d-490e-b5e3-12d64ad7d076</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibraryApp1.BusinessLogic\LibraryApp1.BusinessLogic.csproj" />
    <ProjectReference Include="..\LibraryApp1.DataAccess\LibraryApp1.DataAccess.csproj" />
  </ItemGroup>

</Project>
